# Generated by Django 3.1.5 on 2022-06-07 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220325_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 6, 7, 20, 24, 42, 303297)),
        ),
    ]
