# Generated by Django 3.1.5 on 2022-02-21 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220214_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 2, 21, 10, 57, 58, 734332)),
        ),
    ]
