# Generated by Django 3.1.5 on 2022-02-28 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220225_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 2, 28, 17, 34, 19, 541512)),
        ),
    ]
